### ISSUE TITLE
ffmpeg command can be simplified (now copies cover art too!)

### ISSUE THREAD

**Issue by Erudition** [audible-tools/audible-tools.github.io#6]
https://superuser.com/a/1515121

**Comment by JKamsker** [comment]
Could you please elaborate your request?

**Comment by Erudition** [comment]
I'm not sure what more there is to say, I fit it all in the title.
It's more of a suggestion than a request. To rephrase:
The current version spits out a long ffmpeg command like
`ffmpeg.exe -y -activation_bytes 00000000 -i  ".\input.aax" -map_metadata 0 -id3v2_version 3 -codec:a copy -vn "output.m4b"`
But now, as described in the QA linked, it can simply be
`ffmpeg -activation_bytes 00000000 -i input.aax -c copy output.m4b`
which has the additional benefit of preserving cover art.

**Comment by csandman** [comment]
I actually came here to post the same issue, and oddly enough, that's my StackExchange post you linked to @Erudition haha.

But yeah, in FFmpeg version 4.1 they added native support for copying album artwork when decrypting AAX files, so the request is to change the command run by `ffmpeg.wasm` in the browser to allow this.  In order to do it you just have to remove the `-vn` flag and change `-codec:a copy` to `-c copy`.

As far as the other flags like `map_metadata` and `id3v2_version`, I'm not sure if you need those, but I've never really needed them when running this conversion process locally.

**Comment by JKamsker** [comment]
@Erudition @csandman  PR's welcome

**Comment by JKamsker** [comment]
@csandman Online conversion is broken with your patch

**Comment by JKamsker** [comment]
@csandman Fixed it for you.https://github.com/audible-tools/audible-tools.github.io/commit/9af760f87cda0be80739d1be7d4d6a1d301a5224

**Comment by csandman** [comment]
Awesome! Sorry it didn't work in browser, I could not for the life of me get ffmpeg.wasm to work in the browser, even before I changed anything. I'm glad you got it worked out.

**Comment by JKamsker** [comment]
I guess you missed the cors headers required for sharedarraybuffers

**Comment by csandman** [comment]
how do you set that up locally? does it not run out of the box?

**Comment by JKamsker** [comment]
@csandman 
https://github.com/ffmpegwasm/react-app/commit/248e707338484eb331bd48762b964b52fea3ec86
